### ISSUE TITLE
"Configuration of Amazon SQS queues" not shown in "Configure System" using Jenkins 2.8

### ISSUE THREAD

**Issue by NiclasDaniels** [jenkinsci/scm-sqs-plugin#2]
I successfully downloaded and installed the SCM SQS Plugin for Jenkins and rebooted but when I tried to access the configuration for the plugin: Jenkins > Manage Jenkins > Configure System, I couldn't find any fields related to this plugin at all.

I'm using an AWS EC2 instance: Amazon Linux AMI 2016.03.2 x86_64 HVM GP2. I installed Jenkins using the installation instructions for Red Hat distributions, see [here](https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Red+Hat+distributions), resulting in version 2.8 of Jenkins being installed.

**Comment by mpfeiffermway** [comment]
Hi Niclas, thanks again for your feedback.

We've just tested the plugin against our local Jenkins 2.8 test instance and could reproduce the issue. I've already had a look on it on my development machine, looks like its just missing an updated dependency. A fix should be incoming soon.

**Comment by NiclasDaniels** [comment]
Great, thanks! I look forward to trying out the updated version of this plugin.

**Comment by mpfeiffermway** [comment]
I've just released version 1.2 of the plugin.

The new version should become available in the Jenkins Update Center within four hours. Depending on the time your Jenkins installation updates its meta data it may take some additional time before the update is shown.

You can also click on Check Now in Manage Plugins to fetch the latest data from the Update Center. Note that this will have no effect until the Update Center has refreshed its data (every four hours).

**Comment by NiclasDaniels** [comment]
It works fine now on my Jenkins 2.8 instance as well, great! Thanks for updating so swiftly! The only thing I did wrong during the instructions was that I created the SNS/SQS in another region than the CodeCommit region so I couldn't link AWS CodeCommit to the SNS topic since the regions didn't match. My bad. So I had to start over again. Maybe somebody else would benefit from getting a heads-up on the requirement to use the same region (the CodeCommit region) throughout the creation of all services in the instructions, just as a reminder? At the time of writing, CodeCommit is only available in [one region](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/), which is not my preferred region, so I never create services in the CodeCommit region by default, hence my mistake.

**Comment by mpfeiffermway** [comment]
You're right this should definitely be mentioned since it isn't immediately obvious. I'll update the documentation soon (Issue #4). We've also discovered some more bugs internally (writing tickets now), so another update is incoming in a day or two.
